name: "Bug Report"
description: "Report something that is not working through a form."
body:
  - type: markdown
    attributes:
      value: |
        Welcome! This is a form that allows you to write a bug report through a form rather than manually.
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      placeholder: |
        "e.g. 1.21.4"
    validations:
      required: true
  - type: input
    id: datapack-version
    attributes:
      label: Data pack version
      placeholder: |
        "e.g. v2.2.0"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Please explain exacly what the bug is and how did you encounter it."
      placeholder: |
        e.g. When I execute a certain function, it doesn't do anyting.
    validations:
      required: true
assignees: LluisJM
labels: bug
